{
    "mid": "0xCC",
    "parameters": [
        {
            "type": "float",
            "value": 0,
            "label": "t_gps1980"
        },
        {
            "type": "uint8",
            "value": 0,
            "label": "_"
        },
        {
            "type": "uint8",
            "value": 0,
            "label": "_"
        },
        {
            "type": "uint8",
            "value": 0,
            "label": "_"
        },
        {
            "type": "uint8",
            "value": 0,
            "label": "_"
        },
        {
            "type": "uint8",
            "value": 0,
            "label": "_"
        },
        {
            "type": "array",
            "element_type": "uint8",
            "values": [0,0,0],
            "label": "_"
        }
   ]
}