{
    "mid": "0xC3",
    "parameters": [
        {
            "type": "uint8",
            "value": 0,
            "name": "enabled_CMGs"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "GimbalRate"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "GimbalAngle"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "RotorSpeed"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "RotorTorque"
        }
    ]
}