{
    "mid": "0xD1",
    "parameters": [
        {
            "type": "array",
            "element_type": "float",
            "values": [0, 0, 0],
            "name": "w_bwrteci_est"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0, 0, 0, 1],
            "name": "q_eci2body_est"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "gim_w_b"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "gim_phi_b"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0,0,0,0,0,0],
            "name": "w_rotor"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0],
            "name": "mag_field_eci"
        },
        {
            "type": "array",
            "element_type": "float",
            "values": [0,0,0],
            "name": "sun_vec_meas"
        }
    ]
}
